apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: azuremaxcontainer.azurecr.io/httpd-24:v1
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: httpd
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
  - port: 8443
    name: https
  selector:
    app: httpd
